"""
ai_advisor.py -- Sends each finding to an AI model for plain-English
                  remediation advice.

Supported providers (set AI_PROVIDER in .env):
  - "litellm"     - default, uses LiteLLM to support 100+ providers
  - "auto"        - automatically picks the first available API key
  - "custom"      - uses your private enterprise endpoint
  - Native SDKs   - "anthropic", "openai", "gemini", "ollama", "xai", "deepseek"

Data safety:
  Before any finding is sent to a third-party API we strip it down to only
  the keys that are needed for the AI to understand the issue. No raw AWS
  account IDs, ARNs, or internal resource names are forwarded.
"""

import json
import os
import re
import concurrent.futures
import time

from rich.console import Console
from rich.panel import Panel
from adapters import get_provider

console = Console()

# -- Prompt shared by every provider ------------------------------------
SYSTEM_PROMPT = (
    "You are a cloud security expert. First, explain the given AWS security finding "
    "in 2-3 plain English sentences that a junior engineer can understand. "
    "Press Enter twice to start a new paragraph. "
    "Then, provide 2-3 specific remediation steps formatted as bullet points "
    "with brief AWS CLI or Console instructions."
)

# -- Free model list (for reference) ------------------------------------
FREE_MODELS = [
    "meta-llama/llama-3.3-70b-instruct:free",
    "google/gemma-3-27b-it:free",
    "deepseek/deepseek-r1:free",
    "qwen/qwen3-next-80b:free",
    "mistralai/mistral-small-3.1-24b-instruct:free",
    "nvidia/llama-3.1-nemotron-70b-instruct:free",
]

DEFAULT_MODEL = "meta-llama/llama-3.3-70b-instruct:free"

JUDGE_PROMPT = (
    "You are an AI Judge. You will be acting as a cloud security expert reviewing "
    "advice generated by other AI models. Your goal is to review their proposed "
    "remediation steps for an AWS misconfiguration and pick the BEST advice.\n"
    "Look at accuracy, clarity, and safety of the commands.\n\n"
    "You MUST output exactly in the following JSON format and NOTHING else:\n"
    "{\n"
    "  \"winning_model\": \"<name of the model you picked>\",\n"
    "  \"confidence_score\": \"<Low, Medium, or High>\",\n"
    "  \"reasoning\": \"<1 sentence explaining why this model won>\",\n"
    "  \"best_advice\": \"<The actual remediation text from the winning model, slightly improved if needed>\"\n"
    "}"
)


# -- JSON extraction helper (Bug #1 fix) --------------------------------
def _extract_json(raw: str) -> dict:
    """
    Robustly extract a JSON object from raw LLM output.
    Handles:
      - Pure JSON strings
      - JSON wrapped in ```json ... ``` markdown fences
      - JSON buried inside conversational text
    Returns parsed dict, or a safe fallback on failure.
    """
    if not raw or not raw.strip():
        return {
            "winning_model": "Unknown (empty response)",
            "confidence_score": "Unknown",
            "reasoning": "Judge AI returned an empty response.",
            "best_advice": "No advice available.",
        }

    text = raw.strip()

    # Step 1: Strip markdown code fences (```json ... ``` or ``` ... ```)
    fence_pattern = re.compile(r"```(?:json)?\s*\n?(.*?)\n?\s*```", re.DOTALL)
    fence_match = fence_pattern.search(text)
    if fence_match:
        text = fence_match.group(1).strip()

    # Step 2: Try direct parse
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        pass

    # Step 3: Find the first { ... } block using brace-depth counting
    start = text.find("{")
    if start != -1:
        depth = 0
        for i in range(start, len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    candidate = text[start : i + 1]
                    try:
                        return json.loads(candidate)
                    except (json.JSONDecodeError, ValueError):
                        break

    # Step 4: Fallback — return the raw text as advice
    return {
        "winning_model": "Unknown (parse error)",
        "confidence_score": "Unknown",
        "reasoning": "Judge AI output could not be parsed as JSON.",
        "best_advice": raw.strip(),
    }


# -- Data sanitisation --------------------------------------------------
def _sanitise_network(text: str) -> str:
    """
    Replace IPv4 and IPv6 addresses with redaction tags.
    Matches CIDR notation as well (e.g., 0.0.0.0/0).
    """
    if not isinstance(text, str):
        return text

    # IPv4 regex (handles 0.0.0.0/0, 192.168.1.1, etc.)
    ipv4_pattern = r"\b(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?\b"
    text = re.sub(ipv4_pattern, "<IPv4_REDACTED>", text)

    # IPv6 regex (basic support for standard hex notation)
    ipv6_pattern = r"\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}(?:/\d{1,3})?\b"
    text = re.sub(ipv6_pattern, "<IPv6_REDACTED>", text)

    return text


def _sanitise_finding(finding: dict) -> dict:
    """
    Return a COPY of the finding with sensitive info scrubbed so we never
    leak real AWS account IDs, ARNs, or IP addresses to a third-party API.
    """
    safe = {
        "service":  finding.get("service", "Unknown"),
        "issue":    finding.get("issue", "Unknown"),
        "severity": finding.get("severity", "Unknown"),
        "details":  _sanitise_network(finding.get("details", "")),
    }

    # Keep resource_name but mask sensitive patterns
    resource = finding.get("resource_name", "Unknown")
    resource = re.sub(r"\b\d{12}\b", "XXXXXXXXXXXX", resource)
    resource = re.sub(r"arn:aws:[^\"'\s]+", "arn:aws:***REDACTED***", resource)
    safe["resource_name"] = _sanitise_network(resource)

    return safe


# Redundant provider helpers removed in favor of Adapter Pattern.


# Registry moved to get_provider factory.


# -- Comparison Mode Workers --------------------------------------------
def _compare_all_models(finding: dict, prompt: str) -> dict:
    """
    Runs the OpenRouter query on all models specified in COMPARISON_MODELS in parallel.
    Returns a dictionary of format {model_name: "advice text"}.
    """
    models_str = os.getenv("COMPARISON_MODELS", "")
    if not models_str:
        models_str = DEFAULT_MODEL
    
    models = [m.strip() for m in models_str.split(",") if m.strip()]
    if len(models) == 0:
        models = [DEFAULT_MODEL]
        
    results = {}
    
    # Run API calls in parallel to bypass long sequential wait times!
    with concurrent.futures.ThreadPoolExecutor(max_workers=min(len(models), 5)) as executor:
        from adapters.litellm_adapter import LiteLLMAdapter
        # map future to model name
        future_to_model = {
            executor.submit(LiteLLMAdapter(model_override=model).complete, prompt, SYSTEM_PROMPT): model 
            for model in models
        }
        
        for future in concurrent.futures.as_completed(future_to_model):
            model = future_to_model[future]
            try:
                advice = future.result()
                results[model] = advice
            except Exception as e:
                results[model] = f"Error: {e}"
                
    return results

def _run_judge_ai(finding_safe: dict, advice_results: dict) -> dict:
    """
    Passes the results of all models to the Judge AI to pick the winner.
    """
    # Use the configured provider for judging
    judge_provider = get_provider()
    
    prompt = (
        f"Here is the finding:\n{json.dumps(finding_safe, indent=2)}\n\n"
        "Here are the proposed remediation plans from different AI models:\n"
    )
    
    for model, advice in advice_results.items():
        prompt += f"--- MODEL: {model} ---\n{advice}\n\n"
        
    raw_judge_output = judge_provider.complete(prompt, system_prompt=JUDGE_PROMPT, max_tokens=600)
    return _extract_json(raw_judge_output)


# -- Public API ---------------------------------------------------------
def get_ai_advice(findings_list: list) -> list:
    """
    For each finding dict, call the configured AI provider and append an
    'ai_advice' key with the response. Returns the mutated list.
    """
    if not findings_list:
        console.print("[bold yellow]No findings to send to AI Advisor.[/bold yellow]")
        return findings_list

    try:
        provider = get_provider()
    except ValueError as e:
        console.print(f"[bold red]Configuration Error: {e}[/bold red]")
        for finding in findings_list:
            finding["ai_advice"] = "Skipped - check configuration"
        return findings_list

    comparison_mode = os.getenv("COMPARISON_MODE", "false").lower() == "true"

    # Show what we're using
    console.print(
        Panel(
            f"Mode: [bold]{'Comparison' if comparison_mode else 'Standard'}[/bold]\n"
            f"Provider: [cyan]{provider.get_name()}[/cyan]",
            title="AI Advisor",
            border_style="yellow",
        )
    )

    total = len(findings_list)
    for i, finding in enumerate(findings_list):
        if i > 0:
            time.sleep(2)  # Avoid hitting RPM limits on free models
        resource = finding.get("resource_name", "Unknown")
        issue    = finding.get("issue", "Unknown")
        console.print(f"  [{i + 1}/{total}] [cyan]{resource}[/cyan] - {issue}")

        # Sanitise before sending to external API
        safe = _sanitise_finding(finding)
        prompt = f"Finding:\n{json.dumps(safe, indent=2)}"

        try:
            if comparison_mode:
                console.print("       [dim]Querying multiple models in parallel...[/dim]")
                all_advice = _compare_all_models(safe, prompt)
                console.print("       [dim]Models answered! Judging best response...[/dim]")
                judge_result = _run_judge_ai(safe, all_advice)
                
                # Assign the winning logic properly
                best_advice = judge_result.get("best_advice", "Failed to retrieve advice.")
                finding["ai_advice"] = [line.strip() for line in best_advice.split("\n") if line.strip()]
                
                # Save metadata for report mapping
                finding["judge_info"] = {
                    "winning_model": judge_result.get("winning_model", "Unknown"),
                    "confidence_score": judge_result.get("confidence_score", "Unknown"),
                    "reasoning": judge_result.get("reasoning", "")
                }
                
                console.print(f"       [green][Winner: {finding['judge_info']['winning_model']}][/green]")
                console.print(f"       [green][Confidence: {finding['judge_info']['confidence_score']}][/green]")
            else:
                advice = provider.complete(prompt, system_prompt=SYSTEM_PROMPT)
                # Split by newline so JSON saves it as a readable list instead of one long string with \n
                finding["ai_advice"] = [line.strip() for line in advice.split("\n") if line.strip()]
                console.print("       [green][Advice Generated][/green]")
                
        except Exception as e:
            error_msg = str(e)
            if len(error_msg) > 200:
                error_msg = error_msg[:200] + "..."
            # Escape brackets so Rich doesn't parse them as markup
            safe_msg = error_msg.replace("[", "\\[").replace("]", "\\]")
            console.print(f"       [bold red][FAIL] {safe_msg}[/bold red]")
            finding["ai_advice"] = f"Failed ({type(e).__name__})"

    console.print("[bold yellow]AI Advisor complete.[/bold yellow]\n")
    return findings_list


# -- Quick test ---------------------------------------------------------
if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()

    test_findings = [
        {
            "service": "S3",
            "resource_name": "my-test-bucket",
            "issue": "Public Read Access Enabled",
            "severity": "Critical",
            "details": "Bucket policy allows s3:GetObject for principal *",
        }
    ]
    results = get_ai_advice(test_findings)
    for r in results:
        console.print(Panel(r.get("ai_advice", "N/A"), title="AI Advice"))
